name = "Enigmatic Graves"
filename = "EnigmaticGraves-1.6.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3421/782/EnigmaticGraves-1.6.1.jar"
hash-format = "murmur2"
hash = "2766946823"

[update]
[update.curseforge]
file-id = 3421782
project-id = 496030
release-channel = "beta"
