name = "SuperMartijn642's Core Lib"
filename = "supermartijn642corelib-1.0.10a-mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3390/753/supermartijn642corelib-1.0.10a-mc1.16.5.jar"
hash-format = "murmur2"
hash = "937352603"

[update]
[update.curseforge]
file-id = 3390753
project-id = 454372
release-channel = "beta"
