name = "SuperMartijn642's Core Lib"
filename = "supermartijn642corelib-1.0.12-mc1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3413/422/supermartijn642corelib-1.0.12-mc1.16.5.jar"
hash-format = "murmur2"
hash = "572436363"

[update]
[update.curseforge]
file-id = 3413422
project-id = 454372
release-channel = "beta"
